/* Generated By:JavaCC: Do not edit this line. Exp1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Exp1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ORDER_SIGN = 5;
  /** RegularExpression Id. */
  int T_ARTICLE = 6;
  /** RegularExpression Id. */
  int T_BOOK = 7;
  /** RegularExpression Id. */
  int T_MANUAL = 8;
  /** RegularExpression Id. */
  int T_MASTERSTHESIS = 9;
  /** RegularExpression Id. */
  int T_MISC = 10;
  /** RegularExpression Id. */
  int T_PHDTHESIS = 11;
  /** RegularExpression Id. */
  int T_PROCEEDINGS = 12;
  /** RegularExpression Id. */
  int CROSSREF = 13;
  /** RegularExpression Id. */
  int ENTRY_CROSSREF = 14;
  /** RegularExpression Id. */
  int KEYWORDS = 15;
  /** RegularExpression Id. */
  int ENTRY_KEYWORDS = 16;
  /** RegularExpression Id. */
  int FILE = 17;
  /** RegularExpression Id. */
  int ENTRY_FILE = 18;
  /** RegularExpression Id. */
  int DOI = 19;
  /** RegularExpression Id. */
  int ENTRY_DOI = 20;
  /** RegularExpression Id. */
  int URL = 21;
  /** RegularExpression Id. */
  int ENTRY_URL = 22;
  /** RegularExpression Id. */
  int COMMENT = 23;
  /** RegularExpression Id. */
  int ENTRY_COMMENT = 24;
  /** RegularExpression Id. */
  int OWNER = 25;
  /** RegularExpression Id. */
  int ENTRY_OWNER = 26;
  /** RegularExpression Id. */
  int TIMESTAMP = 27;
  /** RegularExpression Id. */
  int ENTRY_TIMESTAMP = 28;
  /** RegularExpression Id. */
  int ABSTRACT = 29;
  /** RegularExpression Id. */
  int ENTRY_ABSTRACT = 30;
  /** RegularExpression Id. */
  int REVIEW = 31;
  /** RegularExpression Id. */
  int ENTRY_REVIEW = 32;
  /** RegularExpression Id. */
  int AUTHOR = 33;
  /** RegularExpression Id. */
  int ENTRY_AUTHOR = 34;
  /** RegularExpression Id. */
  int TITLE = 35;
  /** RegularExpression Id. */
  int ENTRY_TITLE = 36;
  /** RegularExpression Id. */
  int YEAR = 37;
  /** RegularExpression Id. */
  int ENTRY_YEAR = 38;
  /** RegularExpression Id. */
  int PUBLISHER = 39;
  /** RegularExpression Id. */
  int ENTRY_PUBLISHER = 40;
  /** RegularExpression Id. */
  int KEY = 41;
  /** RegularExpression Id. */
  int ENTRY_KEY = 42;
  /** RegularExpression Id. */
  int VOLUME = 43;
  /** RegularExpression Id. */
  int ENTRY_VOLUME = 44;
  /** RegularExpression Id. */
  int NUMBER = 45;
  /** RegularExpression Id. */
  int ENTRY_NUMBER = 46;
  /** RegularExpression Id. */
  int SERIES = 47;
  /** RegularExpression Id. */
  int ENTRY_SERIES = 48;
  /** RegularExpression Id. */
  int ADDRESS = 49;
  /** RegularExpression Id. */
  int ENTRY_ADDRESS = 50;
  /** RegularExpression Id. */
  int EDITION = 51;
  /** RegularExpression Id. */
  int ENTRY_EDITION = 52;
  /** RegularExpression Id. */
  int MONTH = 53;
  /** RegularExpression Id. */
  int ENTRY_MONTH = 54;
  /** RegularExpression Id. */
  int NOTE = 55;
  /** RegularExpression Id. */
  int ENTRY_NOTE = 56;
  /** RegularExpression Id. */
  int ANNOTE = 57;
  /** RegularExpression Id. */
  int ENTRY_ANNNOTE = 58;
  /** RegularExpression Id. */
  int PAGES = 59;
  /** RegularExpression Id. */
  int ENTRY_PAGES = 60;
  /** RegularExpression Id. */
  int JOURNAL = 61;
  /** RegularExpression Id. */
  int ENTRY_JOURNAL = 62;
  /** RegularExpression Id. */
  int ORGANIZATION = 63;
  /** RegularExpression Id. */
  int ENTRY_ORGANIZATION = 64;
  /** RegularExpression Id. */
  int BOOKTITLE = 65;
  /** RegularExpression Id. */
  int ENTRY_BOOKTITLE = 66;
  /** RegularExpression Id. */
  int EDITOR = 67;
  /** RegularExpression Id. */
  int ENTRY_EDITOR = 68;
  /** RegularExpression Id. */
  int SCHOOL = 69;
  /** RegularExpression Id. */
  int ENTRY_SCHOOL = 70;
  /** RegularExpression Id. */
  int TYPE = 71;
  /** RegularExpression Id. */
  int ENTRY_TYPE = 72;
  /** RegularExpression Id. */
  int HOWPUBLISHED = 73;
  /** RegularExpression Id. */
  int ENTRY_HOWPUBLISHED = 74;
  /** RegularExpression Id. */
  int ID = 75;
  /** RegularExpression Id. */
  int INFO_SEPARATOR = 76;
  /** RegularExpression Id. */
  int START_ITEM = 77;
  /** RegularExpression Id. */
  int OPEN_ITEM = 78;
  /** RegularExpression Id. */
  int END_ITEM = 79;
  /** RegularExpression Id. */
  int INFO_OPEN = 80;
  /** RegularExpression Id. */
  int INFO_CLOSE = 81;
  /** RegularExpression Id. */
  int ORDER_ENTRY = 86;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ORDER_TOKENS = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"##\"",
    "\"article\"",
    "\"book\"",
    "\"manual\"",
    "\"masterThesis\"",
    "\"misc\"",
    "\"phdThesis\"",
    "\"proceedings\"",
    "<CROSSREF>",
    "<ENTRY_CROSSREF>",
    "<KEYWORDS>",
    "<ENTRY_KEYWORDS>",
    "<FILE>",
    "<ENTRY_FILE>",
    "<DOI>",
    "<ENTRY_DOI>",
    "<URL>",
    "<ENTRY_URL>",
    "<COMMENT>",
    "<ENTRY_COMMENT>",
    "<OWNER>",
    "<ENTRY_OWNER>",
    "<TIMESTAMP>",
    "<ENTRY_TIMESTAMP>",
    "<ABSTRACT>",
    "<ENTRY_ABSTRACT>",
    "<REVIEW>",
    "<ENTRY_REVIEW>",
    "<AUTHOR>",
    "<ENTRY_AUTHOR>",
    "<TITLE>",
    "<ENTRY_TITLE>",
    "<YEAR>",
    "<ENTRY_YEAR>",
    "<PUBLISHER>",
    "<ENTRY_PUBLISHER>",
    "<KEY>",
    "<ENTRY_KEY>",
    "<VOLUME>",
    "<ENTRY_VOLUME>",
    "<NUMBER>",
    "<ENTRY_NUMBER>",
    "<SERIES>",
    "<ENTRY_SERIES>",
    "<ADDRESS>",
    "<ENTRY_ADDRESS>",
    "<EDITION>",
    "<ENTRY_EDITION>",
    "<MONTH>",
    "<ENTRY_MONTH>",
    "<NOTE>",
    "<ENTRY_NOTE>",
    "<ANNOTE>",
    "<ENTRY_ANNNOTE>",
    "<PAGES>",
    "<ENTRY_PAGES>",
    "<JOURNAL>",
    "<ENTRY_JOURNAL>",
    "<ORGANIZATION>",
    "<ENTRY_ORGANIZATION>",
    "<BOOKTITLE>",
    "<ENTRY_BOOKTITLE>",
    "<EDITOR>",
    "<ENTRY_EDITOR>",
    "<SCHOOL>",
    "<ENTRY_SCHOOL>",
    "<TYPE>",
    "<ENTRY_TYPE>",
    "<HOWPUBLISHED>",
    "<ENTRY_HOWPUBLISHED>",
    "<ID>",
    "\",\"",
    "\"@\"",
    "\"{\"",
    "\"}\"",
    "<INFO_OPEN>",
    "<INFO_CLOSE>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<ORDER_ENTRY>",
  };

}
